// Curse cards (non-stacking, cannot be voluntarily discarded)

window.CURSE_CARDS = [
	{
		id: 'curse_unstable_precision',
		family: 'Unstable Precision',
		name: 'Unstable Precision',
		category: 'Curse',
		effectType: 'stat_modifier',
		effectTarget: 'critChance',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.40, description: '+40% crit chance; non-crits deal -25% damage', flavorText: 'Power at a price.' } }
	},
	{
		id: 'curse_fragile_bulwark',
		family: 'Fragile Bulwark',
		name: 'Fragile Bulwark',
		category: 'Curse',
		effectType: 'stat_modifier',
		effectTarget: 'defense',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.35, description: '+35% defense; 15% chance on hit to break armor (0% defense for 3s)', flavorText: 'Reinforced but brittle.' } }
	},
	{
		id: 'curse_volatile_momentum',
		family: 'Volatile Momentum',
		name: 'Volatile Momentum',
		category: 'Curse',
		effectType: 'conditional',
		effectTarget: 'onKillStackingDamage',
		application: 'conditional',
		duration: 'temporary',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.08, description: '+8% dmg per kill (cap 40%); if no kill in 3s, lose stacks and take 5% max HP per stack (no damage once room is clear)', flavorText: 'Unstoppable force, unstable energy.' } }
	},
	{
		id: 'curse_cursed_volley',
		family: 'Cursed Volley',
		name: 'Cursed Volley',
		category: 'Curse',
		effectType: 'ability_modifier',
		effectTarget: 'projectileCount',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 2, description: '+2 projectiles total; 30% chance projectiles fire randomly; -50% damage per projectile', flavorText: 'Chaotic geometry.' } }
	},
	{
		id: 'curse_blood_pact',
		family: 'Blood Pact',
		name: 'Blood Pact',
		category: 'Curse',
		effectType: 'lifesteal_modifier',
		effectTarget: 'lifesteal',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.15, description: '+15% lifesteal; lifesteal costs 2% max HP/s (stops <20% HP and when room is clear)', flavorText: 'Life for life.' } }
	},
	{
		id: 'curse_berserkers_rage',
		family: 'Berserker\'s Rage',
		name: 'Berserker\'s Rage',
		category: 'Curse',
		effectType: 'conditional',
		effectTarget: 'low_hp_berserk',
		application: 'conditional',
		duration: 'temporary',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.50, description: '+50% damage, +25% move speed below 50% HP; cannot heal above 50%; at <25% HP, 10% chance to self-stun 1s on hit', flavorText: 'Power through pain.' } }
	},
	{
		id: 'curse_fragmented_shield',
		family: 'Fragmented Shield',
		name: 'Fragmented Shield',
		category: 'Curse',
		effectType: 'thorns',
		effectTarget: 'reflect',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.40, description: '+40% damage reflect; 25% chance reflected damage also damages self for 50%', flavorText: 'Broken mirror.' } }
	},
	{
		id: 'curse_overloaded_circuit',
		family: 'Overloaded Circuit',
		name: 'Overloaded Circuit',
		category: 'Curse',
		effectType: 'cooldown',
		effectTarget: 'cdr',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.30, description: '+30% cooldown reduction; using abilities has 15% chance to Overload (double all cooldowns for 5s)', flavorText: 'Too much power, too fast.' } }
	},
	{
		id: 'curse_cursed_speed',
		family: 'Cursed Speed',
		name: 'Cursed Speed',
		category: 'Curse',
		effectType: 'movement',
		effectTarget: 'speed',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.40, description: '+40% movement speed; 20% chance movement reverses for 1s; cannot stop moving', flavorText: 'Too fast to control.' } }
	},
	{
		id: 'curse_phantom_pain',
		family: 'Phantom Pain',
		name: 'Phantom Pain',
		category: 'Curse',
		effectType: 'conditional',
		effectTarget: 'onHitDamageBuff',
		application: 'conditional',
		duration: 'temporary',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.20, description: 'On taking damage: +20% damage for 5s (stacks to 3x); also take 3% max HP as DoT over 3s per hit', flavorText: 'Pain becomes power, but pain is real.' } }
	},
	{
		id: 'curse_unstable_geometry',
		family: 'Unstable Geometry',
		name: 'Unstable Geometry',
		category: 'Curse',
		effectType: 'random_stats',
		effectTarget: 'rotating_boost',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.50, description: 'Random stat (damage/defense/speed) +50% rotates every 10s; others -25%', flavorText: 'Reality fractures.' } }
	},
	{
		id: 'curse_cursed_execution',
		family: 'Cursed Execution',
		name: 'Cursed Execution',
		category: 'Curse',
		effectType: 'conditional',
		effectTarget: 'execute',
		application: 'conditional',
		duration: 'instant',
		nonStacking: true,
		isCurse: true,
		qualityBands: { orange: { value: 0.35, description: 'Execute at 35% HP (boss 15%); 30% chance to fail, deal no damage and self-stun 2s', flavorText: 'Unreliable finisher.' } }
	},
	{
		id: 'curse_doomed_pact',
		family: 'Doomed Pact',
		name: 'Doomed Pact',
		category: 'Curse',
		effectType: 'universal',
		effectTarget: 'all_stats_decay',
		application: 'passive',
		duration: 'persistent',
		nonStacking: true,
		isCurse: true,
		tradeOffs: { statsDecayPerRoom: true, becomesLiabilityAfterRoom16: true, cannotBeRemoved: false },
		qualityBands: { orange: { value: 1, description: '+30% damage, +20% defense, +15% speed; stats decay by 5% per room after room 10 until 0%', flavorText: 'Ultimate power, ultimate price. Time is borrowed, not earned. Power fades with each room.', bonus: { initialDamage: 0.30, initialDefense: 0.20, initialSpeed: 0.15, decayStartRoom: 10, decayPerRoom: 0.05, decayCompleteRoom: 16 } } }
	}
];


