// Team cards (multiplayer only, run-wide modifiers)

window.TEAM_CARDS = [
	{ id: 'team_coordinated_strike', family: 'Coordinated Strike', name: 'Coordinated Strike', category: 'Team', effectType: 'team_modifier', effectTarget: 'proximity_damage', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'complete_10_rooms_together' }, tradeOffs: { requiresStayingNearAllies: true, limitsPositioning: true }, nonStacking: true, qualityBands: { white: { value: 0.10, description: 'All players +10% damage within 200px of ally', flavorText: 'Unity multiplies strength.' } } },
	{ id: 'team_shared_resilience', family: 'Shared Resilience', name: 'Shared Resilience', category: 'Team', effectType: 'team_modifier', effectTarget: 'damage_sharing', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'revive_teammates_5_times' }, tradeOffs: { requiresStayingNearAllies: true, canSpreadDamageToHealthyPlayers: true }, nonStacking: true, qualityBands: { white: { value: 0.30, description: 'Damage split 30% between nearby players (max 2 splits, 150px)', flavorText: 'Shared burden, shared strength.' } } },
	{ id: 'team_synergy_boost', family: 'Synergy Boost', name: 'Synergy Boost', category: 'Team', effectType: 'economy', effectTarget: 'xp_currency_share', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'complete_25_rooms_together' }, nonStacking: true, qualityBands: { white: { value: 0.20, description: 'XP/currency shared +20% (rounded up)', flavorText: 'Together we grow stronger.' } } },
	{ id: 'team_revival_protocol', family: 'Revival Protocol', name: 'Revival Protocol', category: 'Team', effectType: 'revive', effectTarget: 'revive_cooldown', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'revive_teammates_15_times' }, nonStacking: true, qualityBands: { white: { value: -0.30, description: 'Revive cooldown -30%, revive at 60% HP', flavorText: 'No one fights alone.' } } },
	{ id: 'team_elite_bounty', family: 'Elite Bounty', name: 'Elite Bounty', category: 'Team', effectType: 'room_generation', effectTarget: 'elite_frequency', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'clear_3_boss_rooms' }, tradeOffs: { forcesHarderRoomsMoreFrequently: true, lessControlOverDifficultyCurve: true }, nonStacking: true, qualityBands: { white: { value: 1, description: 'Elite rooms guaranteed every 3rd room, +50% card quality in elite rooms', flavorText: 'Seek the greatest challenges.' } } },
	{ id: 'team_challenge_mode', family: 'Challenge Mode', name: 'Challenge Mode', category: 'Team', effectType: 'scaling', effectTarget: 'enemy_scaling', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'reach_room_20_with_4_players' }, tradeOffs: { significantlyHarderEnemies: true, requiresSkilledTeamCoordination: true }, nonStacking: true, qualityBands: { white: { value: 0.25, description: 'Enemies +25% HP/dmg, +100% card quality, +50% shards', flavorText: 'Embrace the ultimate test.' } } },
	{ id: 'team_fortunes_favor', family: 'Fortune\'s Favor', name: 'Fortune\'s Favor', category: 'Team', effectType: 'quality', effectTarget: 'min_quality_band', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'complete_50_rooms_together' }, nonStacking: true, qualityBands: { white: { value: 1, description: 'All card draws +1 quality band minimum', flavorText: 'Luck favors the prepared.' } } },
	{ id: 'team_nexus_link', family: 'Nexus Link', name: 'Nexus Link', category: 'Team', effectType: 'hand', effectTarget: 'shared_hand_size', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'achieve_10_flawless_room_clears' }, nonStacking: true, qualityBands: { white: { value: 1, description: 'Team shares largest hand size upgrade', flavorText: 'Connected minds, shared potential.' } } },
	{ id: 'team_combo_chain', family: 'Combo Chain', name: 'Combo Chain', category: 'Team', effectType: 'conditional', effectTarget: 'multi_kill_damage_stack', application: 'conditional', duration: 'temporary', unlockCondition: { type: 'multiplayer', requirement: 'achieve_25_combo_chains' }, tradeOffs: { requiresCoordinatedMultiKills: true, stacksDecayIfNoCombos: true }, nonStacking: true, qualityBands: { white: { value: 0.02, description: 'Kills within 2s grant +2% stacking damage per player (max 20%)', flavorText: 'Momentum builds together.' } } },
	{ id: 'team_guardian_aura', family: 'Guardian Aura', name: 'Guardian Aura', category: 'Team', effectType: 'aura', effectTarget: 'tank_defense_aura', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'tank_completes_30_rooms' }, tradeOffs: { requiresTankClassInParty: true, requiresStayingNearTank: true, tankMustHaveFortifyForFullBenefit: true }, nonStacking: true, qualityBands: { white: { value: 0.05, description: 'Tank grants +5% defense nearby (+10% if tank has Fortify)', flavorText: 'The shield protects all.' } } },
	{ id: 'team_resource_pool', family: 'Resource Pool', name: 'Resource Pool', category: 'Team', effectType: 'economy', effectTarget: 'pool_split', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'complete_40_rooms_together' }, tradeOffs: { resourcesSplitEvenly: true, highPerformersGetLess: true, lowPerformersGetMore: true }, nonStacking: true, qualityBands: { white: { value: 1, description: 'Currency/XP pooled and split evenly among players', flavorText: 'Shared resources, shared success.' } } },
	{ id: 'team_adaptive_tactics', family: 'Adaptive Tactics', name: 'Adaptive Tactics', category: 'Team', effectType: 'resistance_rotation', effectTarget: 'enemy_resistance', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'reach_room_30_with_4_players' }, tradeOffs: { forcesAdaptation: true, canMakeSomeBuildsLessEffective: true }, nonStacking: true, qualityBands: { white: { value: 5, description: 'Enemy damage type resistance rotates every 5 rooms', flavorText: 'Adapt or perish.' } } },
	{ id: 'team_last_stand', family: 'Last Stand', name: 'Last Stand', category: 'Team', effectType: 'conditional', effectTarget: 'ally_death_buff', application: 'conditional', duration: 'temporary', unlockCondition: { type: 'multiplayer', requirement: 'revive_teammates_30_times' }, tradeOffs: { onlyActivatesWhenTeammateDies: true, requiresDeathToBenefit: true }, nonStacking: true, qualityBands: { white: { value: 0.15, description: 'When a teammate dies, others gain +15% damage until revive', flavorText: 'Fallen comrades inspire greatness.' } } },
	{ id: 'team_shared_burden', family: 'Shared Burden', name: 'Shared Burden', category: 'Team', effectType: 'debuff_spread', effectTarget: 'spread_to_allies', application: 'passive', duration: 'persistent', unlockCondition: { type: 'multiplayer', requirement: 'complete_60_rooms_together' }, tradeOffs: { canSpreadNegativeEffects: true, requiresStayingNearAllies: true }, nonStacking: true, qualityBands: { white: { value: 0.50, description: 'Debuffs spread to nearest ally at 50% effectiveness', flavorText: 'Together we endure.' } } }
];
